### PR TITLE
Formatting

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by Robert-Frampton** [comment]
@jbalsas, can you merge if this looks good?

**Comment by jbalsas** [comment]
Done! We should probably start enforcing issue creation as in other projects for a better changelog in the future 😉

**Comment by bryceosterhaus** [comment]
@jbalsas what can we expect for release cycle of these one-off PRs that get sent? Is there a place to track when it will be released?

**Comment by jbalsas** [comment]
I think I'd like to follow our metal.js proposed release cycle. That is, we release every 2 weeks if there have been changes in that period. If we haven't released in the last 2 weeks, then it should at least wait for the next release day...

We could stablish mondays as the release days, so you'll know that you'll need to wait at least until next monday but no more than to the one after that for a change to be released.

What do you think?

**Comment by bryceosterhaus** [comment]
@jbalsas that sounds good to me.

**Comment by bryceosterhaus** [comment]
For future PRs could we also be sure to add the expected release date once the PR is merged?

**Pull request merged**
