### PR TITLE
Imports metal-debounce

### LINKED ISSUE #38: Move metal-debounce to this repo

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs, that makes a lot of sense! I thought we already had a similar setup and only ran a common saucelabs config and instance. Can you work on that first to make sure we have a stable test infra and then revisit this?

**Comment by diegonvs** [comment]
Sure, now i'm testing :)

**Comment by diegonvs** [comment]
depends of #33

**Comment by jbalsas** [comment]
This is not cleanly rebasing for me... please, re-do on top of `develop` and resend. We're almost there! ;)

**Pull request closed without merging**
