### PR TITLE
Imports metal-scrollspy to this repo

### LINKED ISSUE #33: Move metal-scrollspy to this repo

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Tests are failing here @diegonvs, could we make an attempt at fixing those before merging?

Thanks!

**Comment by jbalsas** [comment]
Hey @diegonvs, this seems to conflict with the saucelabs cleanup. Can you take a look?

**Comment by diegonvs** [comment]
Hey @jbalsas, i'll take a look on this :)

**Comment by jbalsas** [comment]
Pull request submitted to https://github.com/metal/metal-plugins/pull/46. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
