### PR TITLE
Imports metal-css-transitions

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs!

It looks like `packages/metal-useragent/package-lock.json` gets deleted here... and also, the `.eslintrc` is way too big with configuration and different things. Could we reformat it so things look like the rest? We should stick to the defaults as much as possible.

**Comment by jbalsas** [comment]
same conflicts, I merged things in the wrong order 😭

**Comment by diegonvs** [comment]
No problem. i'll send soon 😆

**Comment by diegonvs** [comment]
Resent at #73

**Pull request closed without merging**
