### PR TITLE
WIP: Imports metal-anim

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs, since we already have `metal-promise` in this repo, what do you say we try to fix this one test before merging this one? :)

**Comment by diegonvs** [comment]
I'm going to start this now @jbalsas :grin:

**Comment by jbalsas** [comment]
Hey @diegonvs, this is still failing (and has some conflicts 😢) Can you update this, please? I promise to merge soon!

**Comment by jbalsas** [comment]
I think this is #62 now... closing

**Pull request closed without merging**
