### PR TITLE
Solving #81

### PR DESCRIPTION
**Pull request by diegonvs**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @diegonvs, I think this just needs running `npm run format` to fix the formatting issues. Is this still WIP? Is this all we need for SSR? To do nothing? 😂

**Comment by diegonvs** [comment]
Hey @jbalsas, yes.

- Access localStorage using `jsdom` as #81, now requires an URL that cannot be passed on some applications that are using `metal-storage`. So, main idea was improve the check for localStorage support to won't run in `jsdom` env.

cc @ipeychev , it works for you? I've understood correctly the problem?

**Comment by diegonvs** [comment]
I think that the commit name was not the most appropriate 😂 Accepting suggestions

**Comment by diegonvs** [comment]
We need take some caution by doing this because: https://github.com/metal/metal.js/issues/359

**Pull request merged**
